# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-29 08:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentSorce',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.IntegerField()),
                ('math', models.FloatField()),
                ('english', models.FloatField()),
                ('chiness', models.FloatField()),
            ],
        ),
    ]
