# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-31 14:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SclassCourseRel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', models.IntegerField()),
                ('sclass_id', models.IntegerField()),
                ('teacher_id', models.IntegerField()),
                ('create_time', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 't_sclass_course_rel',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SclassStudentRel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stu_id', models.IntegerField()),
                ('sclass_id', models.IntegerField()),
                ('create_time', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 't_sclass_student_rel',
                'managed': False,
            },
        ),
    ]
