# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-31 03:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserGroup',
            fields=[
                ('uid', models.AutoField(primary_key=True, serialize=False)),
                ('caption', models.CharField(max_length=32, unique=True)),
                ('ctime', models.DateField(auto_now_add=True)),
                ('uptime', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=32, verbose_name='\u7528\u6237\u540d')),
                ('password', models.CharField(help_text='pwd', max_length=60)),
                ('email', models.CharField(max_length=60)),
                ('test', models.EmailField(error_messages={'invalid': '\u8bf7\u8f93\u5165\u5bc6\u7801'}, max_length=19, null=True)),
                ('user_group_id', models.IntegerField(null=True)),
            ],
        ),
    ]
