# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-31 06:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='usergroup',
            table='t_usergroup',
        ),
        migrations.AlterModelTable(
            name='userinfo',
            table='t_userinfo',
        ),
    ]
